name: Update Readme

on:
  # Se ejecuta todos los días a las 08:00 UTC
  schedule:
    - cron: "0 8 * * *"

  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga el repositorio
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Ejecuta un comando
      - name: Run a one-line script
        run: echo "Hello, world!"

      # Ejecuta varios comandos
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
